# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'UI.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.
import time
from PyQt5.QtCore import QThread, pyqtSignal
import Scraping as scraper
from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtGui import QStandardItemModel, QStandardItem
from PyQt5.QtWidgets import QListWidgetItem, QMessageBox
from PyQt5.QtCore import Qt
import pandas as pd
from Sorting_Algorithms import bubble_sort_df,selection_sort_df,insertion_sort_df,quick_sort_df,merge_sort_df,counting_sort_df,radix_sort_df,bucket_sort_df
import threading
from PyQt5.QtCore import QEventLoop
import numpy as np
from Searching_Algorithms import binary_multi_search,linear_multi_filter

output_file = "books.csv"
selected_columns_for_sorting = []
sorting_algorithms = ["Bubble","Selection","Insertion","Quick","Merge","Count","Radix","Bucket"]
data_frame = pd.read_csv(output_file)
temp_df = data_frame
columns_for_filter = []
operations = []
search_values = []
filters = []
pause = False
scraper_thread = None
awaiting_new_condition=False

class Ui_MainWindow(object):
        button_ui = "background-color: #FF9800;\n"
        "    color: white;\n"
        "    font-weight: bold;\n"
        "    font-size: 14px;\n"
        "    border: 2px solid #F57C00;\n"
        "    border-radius: 8px;"
        def setupUi(self, MainWindow):
                MainWindow.setObjectName("MainWindow")
                MainWindow.resize(1366, 780)
                sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
                sizePolicy.setHorizontalStretch(0)
                sizePolicy.setVerticalStretch(0)
                sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
                MainWindow.setSizePolicy(sizePolicy)
                MainWindow.setMaximumSize(QtCore.QSize(16777215, 16777215))
                self.centralwidget = QtWidgets.QWidget(MainWindow)
                self.centralwidget.setMaximumSize(QtCore.QSize(16777215, 16777215))
                self.centralwidget.setObjectName("centralwidget")
                self.verticalLayout_10 = QtWidgets.QVBoxLayout(self.centralwidget)
                self.verticalLayout_10.setObjectName("verticalLayout_10")
                self.main_frame = QtWidgets.QFrame(self.centralwidget)
                self.main_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
                self.main_frame.setFrameShadow(QtWidgets.QFrame.Raised)
                self.main_frame.setObjectName("main_frame")
                self.verticalLayout = QtWidgets.QVBoxLayout(self.main_frame)
                self.verticalLayout.setContentsMargins(0, 0, 0, 0)
                self.verticalLayout.setSpacing(5)
                self.verticalLayout.setObjectName("verticalLayout")
                self.top_frame = QtWidgets.QFrame(self.main_frame)
                sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
                sizePolicy.setHorizontalStretch(0)
                sizePolicy.setVerticalStretch(0)
                sizePolicy.setHeightForWidth(self.top_frame.sizePolicy().hasHeightForWidth())
                self.top_frame.setSizePolicy(sizePolicy)
                self.top_frame.setMinimumSize(QtCore.QSize(0, 60))
                self.top_frame.setMaximumSize(QtCore.QSize(16777215, 60))
                self.top_frame.setStyleSheet("background-color: lightgray;\n"
        "border-radius : 8px;\n"
        "")
                self.top_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
                self.top_frame.setFrameShadow(QtWidgets.QFrame.Raised)
                self.top_frame.setObjectName("top_frame")
                self.label = QtWidgets.QLabel(self.top_frame)
                self.label.setGeometry(QtCore.QRect(10, 10, 1326, 41))
                self.label.setMinimumSize(QtCore.QSize(0, 0))
                font = QtGui.QFont()
                font.setFamily("Segoe UI")
                font.setPointSize(28)
                font.setBold(True)
                font.setWeight(75)
                self.label.setFont(font)
                self.label.setStyleSheet("bgcolor : rgb(255, 255, 255)")
                self.label.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignHCenter)
                self.label.setObjectName("label")
                self.verticalLayout.addWidget(self.top_frame)
                self.middle_frame = QtWidgets.QFrame(self.main_frame)
                self.middle_frame.setStyleSheet("")
                self.middle_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
                self.middle_frame.setFrameShadow(QtWidgets.QFrame.Raised)
                self.middle_frame.setObjectName("middle_frame")
                self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.middle_frame)
                self.horizontalLayout_6.setContentsMargins(0, 0, 0, 0)
                self.horizontalLayout_6.setSpacing(0)
                self.horizontalLayout_6.setObjectName("horizontalLayout_6")
                self.table_frame = QtWidgets.QFrame(self.middle_frame)
                self.table_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
                self.table_frame.setFrameShadow(QtWidgets.QFrame.Raised)
                self.table_frame.setObjectName("table_frame")
                self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.table_frame)
                self.horizontalLayout_7.setObjectName("horizontalLayout_7")
                self.table = QtWidgets.QTableView(self.table_frame)
                self.table.setStyleSheet("background-color: #F2F2F2;            \n"
        "    alternate-background-color: #E6E6E6;   \n"
        "    color: #333333;                        \n"
        "    gridline-color: #CCCCCC;               \n"
        "    selection-background-color: #B0B0B0;   \n"
        "    selection-color: #FFFFFF;           \n"
        "    border: 1px solid #CCCCCC;          \n"
        "    font-size: 13px;\n"
        "    font-weight: normal;\n"
        "    border-radius: 4px;\n"
        "    padding: 2px;")
                self.table.setObjectName("table")
                self.table.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
                self.horizontalLayout_7.addWidget(self.table)
                self.horizontalLayout_6.addWidget(self.table_frame)
                self.right_frame = QtWidgets.QFrame(self.middle_frame)
                sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
                sizePolicy.setHorizontalStretch(0)
                sizePolicy.setVerticalStretch(0)
                sizePolicy.setHeightForWidth(self.right_frame.sizePolicy().hasHeightForWidth())
                self.right_frame.setSizePolicy(sizePolicy)
                self.right_frame.setMinimumSize(QtCore.QSize(0, 0))
                self.right_frame.setMaximumSize(QtCore.QSize(380, 16777215))
                self.right_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
                self.right_frame.setFrameShadow(QtWidgets.QFrame.Raised)
                self.right_frame.setObjectName("right_frame")
                self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.right_frame)
                self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
                self.verticalLayout_3.setSpacing(5)
                self.verticalLayout_3.setObjectName("verticalLayout_3")
                self.frame = QtWidgets.QFrame(self.right_frame)
                self.frame.setEnabled(True)
                self.frame.setStyleSheet("background-color: lightgray;\n"
        "border-radius : 8px;\n"
        "")
                self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
                self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
                self.frame.setObjectName("frame")
                self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.frame)
                self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
                self.verticalLayout_4.setSpacing(0)
                self.verticalLayout_4.setObjectName("verticalLayout_4")
                self.sort_body_frame = QtWidgets.QFrame(self.frame)
                self.sort_body_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
                self.sort_body_frame.setFrameShadow(QtWidgets.QFrame.Raised)
                self.sort_body_frame.setObjectName("sort_body_frame")
                self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.sort_body_frame)
                self.verticalLayout_8.setContentsMargins(0, 0, 0, 0)
                self.verticalLayout_8.setSpacing(0)
                self.verticalLayout_8.setObjectName("verticalLayout_8")
                self.verticalLayout_6 = QtWidgets.QVBoxLayout()
                self.verticalLayout_6.setContentsMargins(0, 0, 0, 0)
                self.verticalLayout_6.setSpacing(0)
                self.verticalLayout_6.setObjectName("verticalLayout_6")
                self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
                self.horizontalLayout_9.setContentsMargins(0, 0, 0, 0)
                self.horizontalLayout_9.setSpacing(0)
                self.horizontalLayout_9.setObjectName("horizontalLayout_9")
                spacerItem = QtWidgets.QSpacerItem(10, 20, QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Minimum)
                self.horizontalLayout_9.addItem(spacerItem)
                self.progress_label_5 = QtWidgets.QLabel(self.sort_body_frame)
                sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
                sizePolicy.setHorizontalStretch(0)
                sizePolicy.setVerticalStretch(0)
                sizePolicy.setHeightForWidth(self.progress_label_5.sizePolicy().hasHeightForWidth())
                self.progress_label_5.setSizePolicy(sizePolicy)
                self.progress_label_5.setMinimumSize(QtCore.QSize(120, 31))
                self.progress_label_5.setMaximumSize(QtCore.QSize(101, 31))
                font = QtGui.QFont()
                font.setFamily("Segoe UI")
                font.setPointSize(14)
                font.setBold(True)
                font.setWeight(75)
                self.progress_label_5.setFont(font)
                self.progress_label_5.setObjectName("progress_label_5")
                self.horizontalLayout_9.addWidget(self.progress_label_5)
                self.sort_algo_combo = QtWidgets.QComboBox(self.sort_body_frame)
                sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
                sizePolicy.setHorizontalStretch(0)
                sizePolicy.setVerticalStretch(0)
                sizePolicy.setHeightForWidth(self.sort_algo_combo.sizePolicy().hasHeightForWidth())
                self.sort_algo_combo.setSizePolicy(sizePolicy)
                self.sort_algo_combo.setMinimumSize(QtCore.QSize(201, 31))
                self.sort_algo_combo.setMaximumSize(QtCore.QSize(201, 31))
                self.sort_algo_combo.setStyleSheet("background-color: white;")
                self.sort_algo_combo.setObjectName("sort_algo_combo")
                self.load_sorting_algo_combo()
                self.horizontalLayout_9.addWidget(self.sort_algo_combo)
                self.verticalLayout_6.addLayout(self.horizontalLayout_9)
                self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
                self.horizontalLayout_10.setContentsMargins(0, 0, 0, 0)
                self.horizontalLayout_10.setSpacing(0)
                self.horizontalLayout_10.setObjectName("horizontalLayout_10")
                self.verticalLayout_5 = QtWidgets.QVBoxLayout()
                self.verticalLayout_5.setContentsMargins(30, 0, 0, 0)
                self.verticalLayout_5.setSpacing(0)
                self.verticalLayout_5.setObjectName("verticalLayout_5")
                self.progress_label_6 = QtWidgets.QLabel(self.sort_body_frame)
                sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
                sizePolicy.setHorizontalStretch(0)
                sizePolicy.setVerticalStretch(0)
                sizePolicy.setHeightForWidth(self.progress_label_6.sizePolicy().hasHeightForWidth())
                self.progress_label_6.setSizePolicy(sizePolicy)
                self.progress_label_6.setMinimumSize(QtCore.QSize(150, 31))
                self.progress_label_6.setMaximumSize(QtCore.QSize(101, 31))
                font = QtGui.QFont()
                font.setFamily("Segoe UI")
                font.setPointSize(14)
                font.setBold(True)
                font.setWeight(75)
                self.progress_label_6.setFont(font)
                self.progress_label_6.setObjectName("progress_label_6")
                self.verticalLayout_5.addWidget(self.progress_label_6)
                self.selected_column_list = QtWidgets.QListWidget(self.sort_body_frame)
                sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
                sizePolicy.setHorizontalStretch(0)
                sizePolicy.setVerticalStretch(0)
                sizePolicy.setHeightForWidth(self.selected_column_list.sizePolicy().hasHeightForWidth())
                self.selected_column_list.setSizePolicy(sizePolicy)
                self.selected_column_list.setMinimumSize(QtCore.QSize(150, 100))
                self.selected_column_list.setMaximumSize(QtCore.QSize(150, 150))
                self.selected_column_list.setStyleSheet("background-color: white;")
                self.selected_column_list.setObjectName("selected_column_list")
                self.verticalLayout_5.addWidget(self.selected_column_list)
                self.horizontalLayout_10.addLayout(self.verticalLayout_5)
                self.verticalLayout_7 = QtWidgets.QVBoxLayout()
                self.verticalLayout_7.setContentsMargins(30, 0, 0, 0)
                self.verticalLayout_7.setSpacing(0)
                self.verticalLayout_7.setObjectName("verticalLayout_7")
                self.progress_label_7 = QtWidgets.QLabel(self.sort_body_frame)
                sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
                sizePolicy.setHorizontalStretch(0)
                sizePolicy.setVerticalStretch(0)
                sizePolicy.setHeightForWidth(self.progress_label_7.sizePolicy().hasHeightForWidth())
                self.progress_label_7.setSizePolicy(sizePolicy)
                self.progress_label_7.setMinimumSize(QtCore.QSize(150, 31))
                self.progress_label_7.setMaximumSize(QtCore.QSize(150, 31))
                font = QtGui.QFont()
                font.setFamily("Segoe UI")
                font.setPointSize(14)
                font.setBold(True)
                font.setWeight(75)
                self.progress_label_7.setFont(font)
                self.progress_label_7.setAlignment(QtCore.Qt.AlignCenter)
                self.progress_label_7.setObjectName("progress_label_7")
                self.verticalLayout_7.addWidget(self.progress_label_7)
                self.column_list = QtWidgets.QListWidget(self.sort_body_frame)
                sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
                sizePolicy.setHorizontalStretch(0)
                sizePolicy.setVerticalStretch(0)
                sizePolicy.setHeightForWidth(self.column_list.sizePolicy().hasHeightForWidth())
                self.column_list.setSizePolicy(sizePolicy)
                self.column_list.setMinimumSize(QtCore.QSize(150, 100))
                self.column_list.setMaximumSize(QtCore.QSize(150, 150))
                self.column_list.setStyleSheet("background-color: white;")
                self.column_list.setObjectName("column_list")
                self.load_column_list()
                self.column_list.itemClicked.connect(self.get_selected_column)
                self.verticalLayout_7.addWidget(self.column_list)
                self.horizontalLayout_10.addLayout(self.verticalLayout_7)
                self.verticalLayout_6.addLayout(self.horizontalLayout_10)
                self.horizontalLayout_11 = QtWidgets.QHBoxLayout()
                self.horizontalLayout_11.setContentsMargins(35, 10, 0, 0)
                self.horizontalLayout_11.setSpacing(0)
                self.horizontalLayout_11.setObjectName("horizontalLayout_11")
                self.progress_label_8 = QtWidgets.QLabel(self.sort_body_frame)
                sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
                sizePolicy.setHorizontalStretch(0)
                sizePolicy.setVerticalStretch(0)
                sizePolicy.setHeightForWidth(self.progress_label_8.sizePolicy().hasHeightForWidth())
                self.progress_label_8.setSizePolicy(sizePolicy)
                self.progress_label_8.setMinimumSize(QtCore.QSize(40, 31))
                self.progress_label_8.setMaximumSize(QtCore.QSize(80, 31))
                font = QtGui.QFont()
                font.setFamily("Segoe UI")
                font.setPointSize(14)
                font.setBold(True)
                font.setWeight(75)
                self.progress_label_8.setFont(font)
                self.progress_label_8.setObjectName("progress_label_8")
                self.horizontalLayout_11.addWidget(self.progress_label_8)
                self.progress_label_9 = QtWidgets.QLabel(self.sort_body_frame)
                sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
                sizePolicy.setHorizontalStretch(0)
                sizePolicy.setVerticalStretch(0)
                sizePolicy.setHeightForWidth(self.progress_label_9.sizePolicy().hasHeightForWidth())
                self.progress_label_9.setSizePolicy(sizePolicy)
                self.progress_label_9.setMinimumSize(QtCore.QSize(40, 31))
                self.progress_label_9.setMaximumSize(QtCore.QSize(120, 31))
                font = QtGui.QFont()
                font.setFamily("Segoe UI")
                font.setPointSize(14)
                font.setBold(True)
                font.setWeight(75)
                self.progress_label_9.setFont(font)
                self.progress_label_9.setObjectName("progress_label_9")
                self.horizontalLayout_11.addWidget(self.progress_label_9)
                spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
                self.horizontalLayout_11.addItem(spacerItem1)
                self.sort_btn = QtWidgets.QPushButton(self.sort_body_frame)
                sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
                sizePolicy.setHorizontalStretch(0)
                sizePolicy.setVerticalStretch(0)
                sizePolicy.setHeightForWidth(self.sort_btn.sizePolicy().hasHeightForWidth())
                self.sort_btn.setSizePolicy(sizePolicy)
                self.sort_btn.setMinimumSize(QtCore.QSize(90, 35))
                font = QtGui.QFont()
                font.setFamily("Segoe UI")
                font.setPointSize(-1)
                font.setBold(True)
                font.setWeight(75)
                self.sort_btn.setFont(font)
                self.sort_btn.setStyleSheet("background-color: #FF9800;\n"
        "    color: white;\n"
        "    font-weight: bold;\n"
        "    font-size: 14px;\n"
        "    border: 2px solid #F57C00;\n"
        "    border-radius: 8px;")
                self.sort_btn.setObjectName("sort_btn")
                self.sort_btn.clicked.connect(self.sort)
                self.horizontalLayout_11.addWidget(self.sort_btn)
                self.reset_sort_btn = QtWidgets.QPushButton(self.sort_body_frame)
                sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
                sizePolicy.setHorizontalStretch(0)
                sizePolicy.setVerticalStretch(0)
                sizePolicy.setHeightForWidth(self.reset_sort_btn.sizePolicy().hasHeightForWidth())
                self.reset_sort_btn.setSizePolicy(sizePolicy)
                self.reset_sort_btn.setMinimumSize(QtCore.QSize(90, 35))
                font = QtGui.QFont()
                font.setFamily("Segoe UI")
                font.setPointSize(-1)
                font.setBold(True)
                font.setWeight(75)
                self.reset_sort_btn.setFont(font)
                self.reset_sort_btn.setStyleSheet("background-color: #9E9E9E;\n"
        "    color: white;\n"
        "    font-weight: bold;\n"
        "    font-size: 14px;\n"
        "    border: 2px solid #616161;\n"
        "    border-radius: 8px;")
                self.reset_sort_btn.setObjectName("reset_sort_btn")
                self.reset_sort_btn.clicked.connect(self.reset_selected_column_list)
                self.horizontalLayout_11.addWidget(self.reset_sort_btn)
                self.verticalLayout_6.addLayout(self.horizontalLayout_11)
                self.verticalLayout_8.addLayout(self.verticalLayout_6)
                self.verticalLayout_4.addWidget(self.sort_body_frame)
                self.verticalLayout_3.addWidget(self.frame)
                self.frame_searching = QtWidgets.QFrame(self.right_frame)
                self.frame_searching.setStyleSheet("background-color: lightgray;\n"
        "border-radius : 8px;\n"
        "")
                self.frame_searching.setFrameShape(QtWidgets.QFrame.StyledPanel)
                self.frame_searching.setFrameShadow(QtWidgets.QFrame.Raised)
                self.frame_searching.setObjectName("frame_searching")
                self.layoutWidget = QtWidgets.QWidget(self.frame_searching)
                self.layoutWidget.setGeometry(QtCore.QRect(12, 11, 384, 242))
                self.layoutWidget.setObjectName("layoutWidget")
                self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.layoutWidget)
                self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
                self.verticalLayout_2.setObjectName("verticalLayout_2")
                self.horizontalLayout_12 = QtWidgets.QHBoxLayout()
                self.horizontalLayout_12.setObjectName("horizontalLayout_12")
                self.progress_label_10 = QtWidgets.QLabel(self.layoutWidget)
                sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
                sizePolicy.setHorizontalStretch(0)
                sizePolicy.setVerticalStretch(0)
                sizePolicy.setHeightForWidth(self.progress_label_10.sizePolicy().hasHeightForWidth())
                self.progress_label_10.setSizePolicy(sizePolicy)
                self.progress_label_10.setMinimumSize(QtCore.QSize(101, 31))
                self.progress_label_10.setMaximumSize(QtCore.QSize(101, 31))
                font = QtGui.QFont()
                font.setFamily("Segoe UI")
                font.setPointSize(14)
                font.setBold(True)
                font.setWeight(75)
                self.progress_label_10.setFont(font)
                self.progress_label_10.setObjectName("progress_label_10")
                self.horizontalLayout_12.addWidget(self.progress_label_10)
                self.search_algo_combo = QtWidgets.QComboBox(self.layoutWidget)
                sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
                sizePolicy.setHorizontalStretch(0)
                sizePolicy.setVerticalStretch(0)
                sizePolicy.setHeightForWidth(self.search_algo_combo.sizePolicy().hasHeightForWidth())
                self.search_algo_combo.setSizePolicy(sizePolicy)
                self.search_algo_combo.setMinimumSize(QtCore.QSize(201, 31))
                self.search_algo_combo.setMaximumSize(QtCore.QSize(201, 31))
                self.search_algo_combo.setStyleSheet("background-color: white;")
                self.search_algo_combo.setObjectName("search_algo_combo")
                self.horizontalLayout_12.addWidget(self.search_algo_combo)
                self.verticalLayout_2.addLayout(self.horizontalLayout_12)
                self.horizontalLayout_15 = QtWidgets.QHBoxLayout()
                self.horizontalLayout_15.setObjectName("horizontalLayout_15")
                self.progress_label_12 = QtWidgets.QLabel(self.layoutWidget)
                sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
                sizePolicy.setHorizontalStretch(0)
                sizePolicy.setVerticalStretch(0)
                sizePolicy.setHeightForWidth(self.progress_label_12.sizePolicy().hasHeightForWidth())
                self.progress_label_12.setSizePolicy(sizePolicy)
                self.progress_label_12.setMinimumSize(QtCore.QSize(101, 31))
                self.progress_label_12.setMaximumSize(QtCore.QSize(101, 31))
                font = QtGui.QFont()
                font.setFamily("Segoe UI")
                font.setPointSize(14)
                font.setBold(True)
                font.setWeight(75)
                self.progress_label_12.setFont(font)
                self.progress_label_12.setObjectName("progress_label_12")
                self.horizontalLayout_15.addWidget(self.progress_label_12)
                self.search_column_combo = QtWidgets.QComboBox(self.layoutWidget)
                sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
                sizePolicy.setHorizontalStretch(0)
                sizePolicy.setVerticalStretch(0)
                sizePolicy.setHeightForWidth(self.search_column_combo.sizePolicy().hasHeightForWidth())
                self.search_column_combo.setSizePolicy(sizePolicy)
                self.search_column_combo.setMinimumSize(QtCore.QSize(201, 31))
                self.search_column_combo.setMaximumSize(QtCore.QSize(201, 31))
                self.search_column_combo.setStyleSheet("background-color: white;")
                self.search_column_combo.setObjectName("search_column_combo")
                self.search_column_combo.currentTextChanged.connect(self.handle_change_columns)
                self.horizontalLayout_15.addWidget(self.search_column_combo)
                self.verticalLayout_2.addLayout(self.horizontalLayout_15)
                self.horizontalLayout_13 = QtWidgets.QHBoxLayout()
                self.horizontalLayout_13.setObjectName("horizontalLayout_13")
                self.progress_label_11 = QtWidgets.QLabel(self.layoutWidget)
                sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
                sizePolicy.setHorizontalStretch(0)
                sizePolicy.setVerticalStretch(0)
                sizePolicy.setHeightForWidth(self.progress_label_11.sizePolicy().hasHeightForWidth())
                self.progress_label_11.setSizePolicy(sizePolicy)
                self.progress_label_11.setMinimumSize(QtCore.QSize(101, 31))
                self.progress_label_11.setMaximumSize(QtCore.QSize(101, 31))
                font = QtGui.QFont()
                font.setFamily("Segoe UI")
                font.setPointSize(14)
                font.setBold(True)
                font.setWeight(75)
                self.progress_label_11.setFont(font)
                self.progress_label_11.setObjectName("progress_label_11")
                self.horizontalLayout_13.addWidget(self.progress_label_11)
                self.search_filter_combo = QtWidgets.QComboBox(self.layoutWidget)
                sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
                sizePolicy.setHorizontalStretch(0)
                sizePolicy.setVerticalStretch(0)
                sizePolicy.setHeightForWidth(self.search_filter_combo.sizePolicy().hasHeightForWidth())
                self.search_filter_combo.setSizePolicy(sizePolicy)
                self.search_filter_combo.setMinimumSize(QtCore.QSize(201, 31))
                self.search_filter_combo.setMaximumSize(QtCore.QSize(201, 31))
                self.search_filter_combo.currentTextChanged.connect(self.handle_change_in_filter)
                from test import prepare_dataframe
                self.search_filter_combo.setStyleSheet("background-color: white;")
                self.search_filter_combo.setObjectName("search_filter_combo")
                self.horizontalLayout_13.addWidget(self.search_filter_combo)
                self.verticalLayout_2.addLayout(self.horizontalLayout_13)
                self.horizontalLayout_17 = QtWidgets.QHBoxLayout()
                self.horizontalLayout_17.setObjectName("horizontalLayout_17")
                spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
                self.horizontalLayout_17.addItem(spacerItem2)
                self.search_box = QtWidgets.QLineEdit(self.layoutWidget)
                sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
                sizePolicy.setHorizontalStretch(0)
                sizePolicy.setVerticalStretch(0)
                sizePolicy.setHeightForWidth(self.search_box.sizePolicy().hasHeightForWidth())
                self.search_box.setSizePolicy(sizePolicy)
                self.search_box.setMinimumSize(QtCore.QSize(360, 31))
                self.search_box.setMaximumSize(QtCore.QSize(301, 31))
                self.search_box.returnPressed.connect(lambda:self.handle_change_in_value(self.search_box.text()))
                self.search_box.setStyleSheet("background-color: white;\n"
        "border-radius : 8px;\n"
        "")
                self.search_box.setObjectName("search_box")
                self.horizontalLayout_17.addWidget(self.search_box)
                self.verticalLayout_2.addLayout(self.horizontalLayout_17)
                self.horizontalLayout_16 = QtWidgets.QHBoxLayout()
                self.horizontalLayout_16.setObjectName("horizontalLayout_16")
                self.and_btn = QtWidgets.QPushButton(self.layoutWidget)
                sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
                sizePolicy.setHorizontalStretch(0)
                sizePolicy.setVerticalStretch(0)
                sizePolicy.setHeightForWidth(self.and_btn.sizePolicy().hasHeightForWidth())
                self.and_btn.setSizePolicy(sizePolicy)
                self.and_btn.setMinimumSize(QtCore.QSize(90, 35))
                font = QtGui.QFont()
                font.setFamily("Segoe UI")
                font.setPointSize(14)
                font.setBold(True)
                font.setWeight(75)
                self.and_btn.setFont(font)
                self.and_btn.setStyleSheet("background-color: white;")
                self.and_btn.setObjectName("and_btn")
                self.horizontalLayout_16.addWidget(self.and_btn)
                self.or_btn = QtWidgets.QPushButton(self.layoutWidget)
                sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
                sizePolicy.setHorizontalStretch(0)
                sizePolicy.setVerticalStretch(0)
                sizePolicy.setHeightForWidth(self.or_btn.sizePolicy().hasHeightForWidth())
                self.or_btn.setSizePolicy(sizePolicy)
                self.or_btn.setMinimumSize(QtCore.QSize(90, 35))
                font = QtGui.QFont()
                font.setFamily("Segoe UI")
                font.setPointSize(14)
                font.setBold(True)
                font.setWeight(75)
                self.or_btn.setFont(font)
                self.or_btn.setStyleSheet("background-color: white;")
                self.or_btn.setObjectName("or_btn")
                self.or_btn.clicked.connect(self.handle_or)
                self.horizontalLayout_16.addWidget(self.or_btn)
                self.or_btn_2 = QtWidgets.QPushButton(self.layoutWidget)
                sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
                sizePolicy.setHorizontalStretch(0)
                prepare_dataframe(data_frame,output_file)
                sizePolicy.setVerticalStretch(0)
                sizePolicy.setHeightForWidth(self.or_btn_2.sizePolicy().hasHeightForWidth())
                self.or_btn_2.setSizePolicy(sizePolicy)
                self.or_btn_2.setMinimumSize(QtCore.QSize(90, 35))
                font = QtGui.QFont()
                font.setFamily("Segoe UI")
                font.setPointSize(14)
                font.setBold(True)
                font.setWeight(75)
                self.or_btn_2.setFont(font)
                self.or_btn_2.setStyleSheet("background-color: white;")
                self.or_btn.clicked.connect(lambda:self.handle_change_in_operator("OR"))
                self.or_btn_2.setObjectName("or_btn_2")
                self.or_btn_2.clicked.connect(self.handle_not)                
                self.horizontalLayout_16.addWidget(self.or_btn_2)
                self.verticalLayout_2.addLayout(self.horizontalLayout_16)
                self.horizontalLayout_14 = QtWidgets.QHBoxLayout()
                self.horizontalLayout_14.setContentsMargins(30, 5, 0, 0)
                self.horizontalLayout_14.setSpacing(0)
                self.horizontalLayout_14.setObjectName("horizontalLayout_14")
                self.progress_label_13 = QtWidgets.QLabel(self.layoutWidget)
                sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
                sizePolicy.setHorizontalStretch(0)
                sizePolicy.setVerticalStretch(0)
                sizePolicy.setHeightForWidth(self.progress_label_13.sizePolicy().hasHeightForWidth())
                self.progress_label_13.setSizePolicy(sizePolicy)
                self.progress_label_13.setMinimumSize(QtCore.QSize(80, 31))
                self.progress_label_13.setMaximumSize(QtCore.QSize(80, 31))
                font = QtGui.QFont()
                font.setFamily("Segoe UI")
                font.setPointSize(14)
                font.setBold(True)
                font.setWeight(75)
                self.progress_label_13.setFont(font)
                self.progress_label_13.setObjectName("progress_label_13")
                self.horizontalLayout_14.addWidget(self.progress_label_13)
                self.progress_label_14 = QtWidgets.QLabel(self.layoutWidget)
                sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
                sizePolicy.setHorizontalStretch(0)
                sizePolicy.setVerticalStretch(0)
                sizePolicy.setHeightForWidth(self.progress_label_14.sizePolicy().hasHeightForWidth())
                self.progress_label_14.setSizePolicy(sizePolicy)
                self.progress_label_14.setMinimumSize(QtCore.QSize(80, 31))
                self.progress_label_14.setMaximumSize(QtCore.QSize(80, 31))
                font = QtGui.QFont()
                font.setFamily("Segoe UI")
                font.setPointSize(14)
                font.setBold(True)
                font.setWeight(75)
                self.progress_label_14.setFont(font)
                self.progress_label_14.setObjectName("progress_label_14")
                self.horizontalLayout_14.addWidget(self.progress_label_14)
                spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
                self.horizontalLayout_14.addItem(spacerItem3)
                self.pushButton_6 = QtWidgets.QPushButton(self.layoutWidget)
                sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
                sizePolicy.setHorizontalStretch(0)
                sizePolicy.setVerticalStretch(0)
                sizePolicy.setHeightForWidth(self.pushButton_6.sizePolicy().hasHeightForWidth())
                self.pushButton_6.setSizePolicy(sizePolicy)
                self.pushButton_6.setMinimumSize(QtCore.QSize(90, 35))
                self.pushButton_6.clicked.connect(lambda:self.handle_search())
                font = QtGui.QFont()
                font.setFamily("Segoe UI")
                font.setPointSize(-1)
                font.setBold(True)
                font.setWeight(75)
                self.pushButton_6.setFont(font)
                self.pushButton_6.setStyleSheet("background-color: #FF9800;\n"
        "    color: white;\n"
        "    font-weight: bold;\n"
        "    font-size: 14px;\n"
        "    border: 2px solid #F57C00;\n"
        "    border-radius: 8px;")
                self.pushButton_6.setObjectName("pushButton_6")
                self.horizontalLayout_14.addWidget(self.pushButton_6)
                self.pushButton_7 = QtWidgets.QPushButton(self.layoutWidget)
                sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
                sizePolicy.setHorizontalStretch(0)
                sizePolicy.setVerticalStretch(0)
                sizePolicy.setHeightForWidth(self.pushButton_7.sizePolicy().hasHeightForWidth())
                self.pushButton_7.setSizePolicy(sizePolicy)
                self.pushButton_7.setMinimumSize(QtCore.QSize(90, 35))
                font = QtGui.QFont()
                font.setFamily("Segoe UI")
                font.setPointSize(-1)
                font.setBold(True)
                font.setWeight(75)
                self.pushButton_7.setFont(font)
                self.pushButton_7.setStyleSheet("background-color: #9E9E9E;\n"
        "    color: white;\n"
        "    font-weight: bold;\n"
        "    font-size: 14px;\n"
        "    border: 2px solid #616161;\n"
        "    border-radius: 8px;")
                self.pushButton_7.setObjectName("pushButton_7")
                self.horizontalLayout_14.addWidget(self.pushButton_7)
                self.verticalLayout_2.addLayout(self.horizontalLayout_14)
                self.verticalLayout_3.addWidget(self.frame_searching)
                self.horizontalLayout_6.addWidget(self.right_frame)
                self.verticalLayout.addWidget(self.middle_frame)
                self.bottom_frame = QtWidgets.QFrame(self.main_frame)
                sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
                sizePolicy.setHorizontalStretch(0)
                sizePolicy.setVerticalStretch(0)
                sizePolicy.setHeightForWidth(self.bottom_frame.sizePolicy().hasHeightForWidth())
                self.bottom_frame.setSizePolicy(sizePolicy)
                self.bottom_frame.setMinimumSize(QtCore.QSize(0, 50))
                self.bottom_frame.setMaximumSize(QtCore.QSize(16777215, 80))
                self.bottom_frame.setStyleSheet("background-color: lightgray;\n"
        "border-radius : 8px;\n"
        "")
                self.bottom_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
                self.bottom_frame.setFrameShadow(QtWidgets.QFrame.Raised)
                self.bottom_frame.setObjectName("bottom_frame")
                self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.bottom_frame)
                self.horizontalLayout_5.setContentsMargins(-1, 0, 0, 30)
                self.horizontalLayout_5.setObjectName("horizontalLayout_5")
                self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
                self.horizontalLayout_2.setContentsMargins(5, 5, 5, 5)
                self.horizontalLayout_2.setObjectName("horizontalLayout_2")
                self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
                self.horizontalLayout_4.setContentsMargins(5, 5, 5, 5)
                self.horizontalLayout_4.setObjectName("horizontalLayout_4")
                self.progress_label_2 = QtWidgets.QLabel(self.bottom_frame)
                sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
                sizePolicy.setHorizontalStretch(0)
                sizePolicy.setVerticalStretch(0)
                sizePolicy.setHeightForWidth(self.progress_label_2.sizePolicy().hasHeightForWidth())
                self.progress_label_2.setSizePolicy(sizePolicy)
                self.progress_label_2.setMinimumSize(QtCore.QSize(150, 31))
                self.progress_label_2.setMaximumSize(QtCore.QSize(150, 31))
                font = QtGui.QFont()
                font.setFamily("Segoe UI")
                font.setPointSize(14)
                font.setBold(True)
                font.setWeight(75)
                self.progress_label_2.setFont(font)
                self.progress_label_2.setObjectName("progress_label_2")
                self.horizontalLayout_4.addWidget(self.progress_label_2)
                self.pages_label = QtWidgets.QLabel(self.bottom_frame)
                self.pages_label.setMinimumSize(QtCore.QSize(60, 31))
                self.pages_label.setMaximumSize(QtCore.QSize(60, 31))
                font = QtGui.QFont()
                font.setFamily("Segoe UI")
                font.setPointSize(14)
                font.setBold(False)
                font.setWeight(50)
                self.pages_label.setFont(font)
                self.pages_label.setObjectName("pages_label")
                self.horizontalLayout_4.addWidget(self.pages_label)
                self.horizontalLayout_2.addLayout(self.horizontalLayout_4)
                self.progress_label = QtWidgets.QLabel(self.bottom_frame)
                self.progress_label.setMinimumSize(QtCore.QSize(101, 31))
                self.progress_label.setMaximumSize(QtCore.QSize(101, 31))
                font = QtGui.QFont()
                font.setFamily("Segoe UI")
                font.setPointSize(14)
                font.setBold(True)
                font.setWeight(75)
                self.progress_label.setFont(font)
                self.progress_label.setObjectName("progress_label")
                self.horizontalLayout_2.addWidget(self.progress_label)
                self.progress_bar = QtWidgets.QProgressBar(self.bottom_frame)
                sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
                sizePolicy.setHorizontalStretch(0)
                sizePolicy.setVerticalStretch(0)
                sizePolicy.setHeightForWidth(self.progress_bar.sizePolicy().hasHeightForWidth())
                self.progress_bar.setSizePolicy(sizePolicy)
                self.progress_bar.setMinimumSize(QtCore.QSize(471, 31))
                self.progress_bar.setMaximumSize(QtCore.QSize(471, 31))
                self.load_search_filter_combo()
                self.load_searching_algo_combo()
                self.progress_bar.setMinimum(0)
                self.progress_bar.setMaximum(25000)

                self.progress_bar.setStyleSheet("QProgressBar {\n"
        "    background-color: #EDE3C8;\n"
        "    border: 1px solid #C4A484;\n"
        "    border-radius: 5px;\n"
        "    text-align: center;\n"
        "    color: #4B2E2E;\n"
        "    font-weight: bold;\n"
        "}\n"
        "\n"
        "QProgressBar::chunk {\n"
        "    background-color: #C4A484;\n"
        "    border-radius: 5px;\n"
        "}\n"
        "")
                self.progress_bar.setProperty("value", 24)
                self.progress_bar.setObjectName("progress_bar")
                self.horizontalLayout_2.addWidget(self.progress_bar)
                self.horizontalLayout_5.addLayout(self.horizontalLayout_2)
                spacerItem4 = QtWidgets.QSpacerItem(171, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
                self.horizontalLayout_5.addItem(spacerItem4)
                self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
                self.horizontalLayout_3.setContentsMargins(5, 5, 5, 5)
                self.horizontalLayout_3.setObjectName("horizontalLayout_3")
                spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
                self.horizontalLayout_3.addItem(spacerItem5)
                self.start_btn = QtWidgets.QPushButton(self.bottom_frame)
                sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
                sizePolicy.setHorizontalStretch(0)
                sizePolicy.setVerticalStretch(0)
                sizePolicy.setHeightForWidth(self.start_btn.sizePolicy().hasHeightForWidth())
                self.start_btn.setSizePolicy(sizePolicy)
                self.start_btn.setMinimumSize(QtCore.QSize(90, 35))
                font = QtGui.QFont()
                font.setFamily("Segoe UI")
                font.setPointSize(-1)
                font.setBold(True)
                font.setWeight(75)
                self.start_btn.setFont(font)
                self.start_btn.setStyleSheet("background-color: #4CAF50;\n"
        "color: white;\n"
        "font-weight: bold;\n"
        "    font-size: 14px;\n"
        "    border: 2px solid #388E3C;\n"
        "    border-radius: 8px;")
                self.start_btn.setObjectName("start_btn")
                self.horizontalLayout_3.addWidget(self.start_btn)
                self.pause_btn = QtWidgets.QPushButton(self.bottom_frame)
                sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
                sizePolicy.setHorizontalStretch(0)
                sizePolicy.setVerticalStretch(0)
                sizePolicy.setHeightForWidth(self.pause_btn.sizePolicy().hasHeightForWidth())
                self.pause_btn.setSizePolicy(sizePolicy)
                self.pause_btn.setMinimumSize(QtCore.QSize(90, 35))
                font = QtGui.QFont()
                font.setFamily("Segoe UI")
                font.setPointSize(-1)
                font.setBold(True)
                font.setWeight(75)
                self.pause_btn.setFont(font)
                self.pause_btn.setStyleSheet("background-color: #F44336;\n"
        "    color: white;\n"
        "    font-weight: bold;\n"
        "    font-size: 14px;\n"
        "    border: 2px solid #D32F2F;\n"
        "    border-radius: 8px;")
                self.pause_btn.setObjectName("pause_btn")
                self.horizontalLayout_3.addWidget(self.pause_btn)
                self.load_btn = QtWidgets.QPushButton(self.bottom_frame)
                sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
                sizePolicy.setHorizontalStretch(0)
                sizePolicy.setVerticalStretch(0)
                sizePolicy.setHeightForWidth(self.load_btn.sizePolicy().hasHeightForWidth())
                self.load_btn.setSizePolicy(sizePolicy)
                self.load_btn.clicked.connect(lambda : self.load_csv(pd.read_csv(output_file)))
                self.load_btn.setMinimumSize(QtCore.QSize(90, 35))
                font = QtGui.QFont()
                font.setFamily("Segoe UI")
                font.setPointSize(-1)
                font.setBold(True)
                font.setWeight(75)
                self.load_btn.setFont(font)
                self.load_btn.setStyleSheet("background-color: #2196F3;\n"
        "    color: white;\n"
        "    font-weight: bold;\n"
        "    font-size: 16px;\n"
        "    border: 2px solid #1976D2;\n"
        "    border-radius: 8px;")
                self.load_btn.setObjectName("load_btn")
                self.horizontalLayout_3.addWidget(self.load_btn)
                self.horizontalLayout_5.addLayout(self.horizontalLayout_3)
                self.verticalLayout.addWidget(self.bottom_frame)
                self.verticalLayout.setStretch(1, 1)
                self.verticalLayout_10.addWidget(self.main_frame)
                MainWindow.setCentralWidget(self.centralwidget)
                self.menubar = QtWidgets.QMenuBar(MainWindow)
                self.menubar.setGeometry(QtCore.QRect(0, 0, 1366, 21))
                self.menubar.setObjectName("menubar")
                MainWindow.setMenuBar(self.menubar)
                self.statusbar = QtWidgets.QStatusBar(MainWindow)
                self.statusbar.setObjectName("statusbar")
                MainWindow.setStatusBar(self.statusbar)

                self.retranslateUi(MainWindow)
                QtCore.QMetaObject.connectSlotsByName(MainWindow)

        def retranslateUi(self, MainWindow):
                _translate = QtCore.QCoreApplication.translate
                MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
                self.label.setText(_translate("MainWindow", "Fiction Books From Readings.com"))
                self.progress_label_5.setText(_translate("MainWindow", "Sort By : "))
                self.progress_label_6.setText(_translate("MainWindow", "Selected Column"))
                self.progress_label_7.setText(_translate("MainWindow", "Select Column"))
                self.progress_label_8.setText(_translate("MainWindow", "Time : "))
                self.progress_label_9.setText(_translate("MainWindow", "0"))
                self.sort_btn.setText(_translate("MainWindow", "Sort"))
                self.reset_sort_btn.setText(_translate("MainWindow", "Reset"))
                self.progress_label_10.setText(_translate("MainWindow", "Algorithm  :"))
                self.progress_label_12.setText(_translate("MainWindow", "Search By :"))
                self.progress_label_11.setText(_translate("MainWindow", "Filter         : "))
                self.and_btn.setText(_translate("MainWindow", "And"))
                self.and_btn.clicked.connect(self.handle_and)
                self.or_btn.setText(_translate("MainWindow", "Or"))
                self.load_searching_column_combo()
                self.or_btn_2.setText(_translate("MainWindow", "Not"))
                self.progress_label_13.setText(_translate("MainWindow", "Time : "))
                self.progress_label_14.setText(_translate("MainWindow", "0"))
                self.pushButton_6.setText(_translate("MainWindow", "Search"))
                self.pushButton_7.setText(_translate("MainWindow", "Reset"))
                self.pushButton_7.clicked.connect(self.reset_search)
                self.progress_label_2.setText(_translate("MainWindow", "Books Loaded : "))
                self.pages_label.setText(_translate("MainWindow", "25000"))
                self.progress_label.setText(_translate("MainWindow", "Progress : "))
                self.start_btn.setText(_translate("MainWindow", "Start"))
                self.start_btn.clicked.connect(self.start)
                self.pause_btn.setText(_translate("MainWindow", "Pause"))
                self.pause_btn.clicked.connect(self.pause)
                self.load_btn.setText(_translate("MainWindow", "Load"))
                self.reset_fields()

        def load_csv(self,data):

                df = data
 
                model = QStandardItemModel()
                columns = data.columns.to_list()
                model.setHorizontalHeaderLabels(columns)

                for i,row in enumerate(df.itertuples(index = False)):
                       items = [QStandardItem(str(x)) for x in row]
                       model.appendRow(items)
                       self.progress_bar.setValue(min(i, 25000))
                       QtWidgets.QApplication.processEvents()
                
                self.table.setModel(model)
                self.table.resizeColumnsToContents()
                length = len(df) - 1
                self.pages_label.setText(str(length))
          
        def load_column_list(self):
                df = pd.read_csv(output_file)
                columns = df.columns
                for column in columns:
                      item = QListWidgetItem(column)
                      item.setTextAlignment(Qt.AlignCenter)
                      self.column_list.addItem(item)

        def get_selected_column(self,recieved_item):
                if(recieved_item.text() not in selected_columns_for_sorting):
                        selected_columns_for_sorting.append(recieved_item.text())
                        item = QListWidgetItem(recieved_item.text())
                        item.setTextAlignment(Qt.AlignCenter)
                        self.selected_column_list.addItem(item)    
                else:
                       QMessageBox.information(None, "Error", "You cannot select same column twice")       

        def reset_selected_column_list(self):
               global data_frame
               selected_columns_for_sorting.clear()
               self.selected_column_list.clear()
               data_frame = pd.read_csv(output_file)

        def load_sorting_algo_combo(self):
               for algo in sorting_algorithms:
                      self.sort_algo_combo.addItem(algo)
              
        def sort(self):
                global data_frame
                start_time = time.time()
                self.sort_btn.setEnabled(False)
                self.sort_btn.setStyleSheet("background-color: lightgray;")
                algorithm = self.sort_algo_combo.currentText()
                df = data_frame.copy()

                for col in reversed(selected_columns_for_sorting):
                        if algorithm in ["Bubble", "Insertion", "Merge"]:
                                if algorithm == "Bubble":
                                        sort_func = bubble_sort_df
                                elif algorithm == "Insertion":
                                        sort_func = insertion_sort_df
                                elif algorithm == "Merge":
                                        sort_func = merge_sort_df

                                sorter = SortingThread(df, col, sort_func)
                                loop = QEventLoop()
                                sorter.finished.connect(lambda sorted_df: (df.update(sorted_df), loop.quit()))
                                sorter.start()
                                loop.exec_()

                        elif algorithm in ["Selection", "Quick"]:
                                if algorithm == "Selection":
                                        sort_func = selection_sort_df
                                else:
                                        sort_func = quick_sort_df
                                df = self._unstable_multi_sort(df, col, sort_func)

                        else:
                                if col not in ["Dimensions","Title","Publisher"]:
                                        if algorithm == "Count":
                                                df = counting_sort_df(df, col)
                                        elif algorithm == "Radix":
                                                df = radix_sort_df(df, col)
                                        elif algorithm == "Bucket":
                                                df = bucket_sort_df(df, col)
                                else:
                                      QMessageBox.information(None,"Error","For numberic data only")

                end_time = time.time()
                total_time = round((end_time - start_time) * 1000,1)
                self.progress_label_9.setText(str(total_time) + " ms")
                self.load_csv(df)
                data_frame = df
                self.sort_btn.setEnabled(True)
                self.sort_btn.setStyleSheet(self.button_ui)

        def _unstable_multi_sort(self, df, column, sort_func):
                col_idx = df.columns.get_loc(column)
                sorted_df = sort_func(df, column)
                df_sorted_values = sorted_df.values.copy()
                unique_vals = np.unique(df_sorted_values[:, col_idx])
                new_rows = []
                for val in unique_vals:
                        group_rows = df_sorted_values[df_sorted_values[:, col_idx] == val]
                        if len(group_rows) > 1:
                                group_df = pd.DataFrame(group_rows, columns=df.columns)
                                group_rows = sort_func(group_df, column).values
                                new_rows.append(group_rows)
                        else:
                                new_rows.append(group_rows)

                df_final = pd.DataFrame(np.vstack(new_rows), columns=df.columns)
                return df_final

        def load_searching_algo_combo(self):
               self.search_algo_combo.addItem("Linear")
               self.search_algo_combo.addItem("Binary")

        def load_search_filter_combo(self):
               self.search_filter_combo.addItem("contains")
               self.search_filter_combo.addItem("endswith")
               self.search_filter_combo.addItem("startswith")
               self.search_filter_combo.addItem("=")
               self.search_filter_combo.addItem(">")
               self.search_filter_combo.addItem("<")

        def load_searching_column_combo(self):
               columns = data_frame.columns.tolist()
               for column in columns:
                      if column != "Dimensions":
                        self.search_column_combo.addItem(column)
                
        
        def handle_change_columns(self, text):
            global awaiting_new_condition

            if text.strip(): 
                if awaiting_new_condition:
                    columns_for_filter.append(text)
                    awaiting_new_condition = False
                elif len(columns_for_filter) < len(search_values):
                    columns_for_filter.append(text)
                else:
                    if columns_for_filter:
                        columns_for_filter[-1] = text
                    else:
                        columns_for_filter.append(text)

            self.check_all_ready()


        def handle_change_in_filter(self, text):
            global awaiting_new_condition

            if text.strip():
                if awaiting_new_condition:
                    filters.append(text)
                    awaiting_new_condition = False
                elif len(filters) < len(search_values):
                    filters.append(text)
                else:
                    if filters:
                        filters[-1] = text
                    else:
                        filters.append(text)

            self.check_all_ready()


        def handle_change_in_value(self, text):
            global awaiting_new_condition

            if text.strip():
                if awaiting_new_condition:
                    search_values.append(text)
                    awaiting_new_condition = False
                elif len(search_values) <= len(columns_for_filter):
                    search_values.append(text)
                else:
                    if search_values:
                        search_values[-1] = text
                    else:
                        search_values.append(text)

            self.check_all_ready()


        def check_all_ready(self):
                if (
                        len(columns_for_filter) == len(filters) == len(search_values)
                        and len(columns_for_filter) > 0
                ):
                        self.allow_btn()


        def handle_change_in_operator(self, text):
            global awaiting_new_condition
            if len(operations) < len(search_values):
                operations.append(text)
            else:
                if operations:
                    operations[-1] = text
                else:
                    operations.append(text)

            awaiting_new_condition = True

            self.and_btn.setEnabled(False)
            self.and_btn.setStyleSheet("background-color: lightgray;")

            self.or_btn.setEnabled(False)
            self.or_btn.setStyleSheet("background-color: lightgray;")

            self.or_btn_2.setEnabled(False)
            self.or_btn_2.setStyleSheet("background-color: lightgray;")

            self.pushButton_6.setEnabled(False)
            self.pushButton_6.setStyleSheet("background-color: lightgray;")


        def handle_and(self):
            self.handle_change_in_operator("AND")
            self.reset_fields()


        def handle_or(self):
            self.handle_change_in_operator("OR")
            self.reset_fields()


        def handle_not(self):
            self.handle_change_in_operator("NOT")
            self.reset_fields()


        def allow_btn(self):
            self.and_btn.setEnabled(True)
            self.and_btn.setStyleSheet("")

            self.or_btn.setEnabled(True)
            self.or_btn.setStyleSheet("")

            self.or_btn_2.setEnabled(True)
            self.or_btn_2.setStyleSheet("")

            self.pushButton_6.setEnabled(True)
            self.pushButton_6.setStyleSheet(self.button_ui)


        def reset_fields(self):
            """Clear input fields for next condition"""
            self.search_column_combo.setCurrentIndex(-1)
            self.search_filter_combo.setCurrentIndex(-1)
            self.search_box.clear()

            self.and_btn.setEnabled(False)
            self.and_btn.setStyleSheet("background-color: lightgray;")

            self.or_btn.setEnabled(False)
            self.or_btn.setStyleSheet("background-color: lightgray;")

            self.or_btn_2.setEnabled(False)
            self.or_btn_2.setStyleSheet("background-color: lightgray;")

            self.pushButton_6.setEnabled(False)
            self.pushButton_6.setStyleSheet("background-color: lightgray;")


        def reset_search(self):
            print(columns_for_filter)
            print(filters)
            print(search_values)
            search_values.clear()
            filters.clear()
            columns_for_filter.clear()
            operations.clear()

            self.search_column_combo.setCurrentIndex(-1)
            self.search_filter_combo.setCurrentIndex(-1)
            self.search_box.clear()

            self.and_btn.setEnabled(False)
            self.and_btn.setStyleSheet("background-color: lightgray;")

            self.or_btn.setEnabled(False)
            self.or_btn.setStyleSheet("background-color: lightgray;")

            self.or_btn_2.setEnabled(False)
            self.or_btn_2.setStyleSheet("background-color: lightgray;")

            self.pushButton_6.setEnabled(True)
            self.pushButton_6.setStyleSheet(self.button_ui)

        def handle_search(self):
            global data_frame
            start = time.time()
            if self.search_algo_combo.currentText() == "Linear":
                df = linear_multi_filter(temp_df, columns_for_filter, filters, operations, search_values)
            else:
                df = binary_multi_search(temp_df, columns_for_filter, filters, operations, search_values)
            end = time.time()
            total_time = (end - start) * 1000
            self.progress_label_14.setText(str(total_time) + "ms")
            self.load_csv(df)
            if len(df) > 1:
                data_frame = df

        def start(self):
                """Starts the scraping process in a background thread."""
                global scraper_thread
                if scraper_thread is None or not scraper_thread.is_alive():
                        scraper_thread = threading.Thread(target=scraper.start_scraping)
                        scraper_thread.start()
                        print("Scraping thread started.")

        def pause(self):
                if pause:
                        scraper.set_pause(False)
                        pause = False
                        print("Scraping resumeed signal sent.")
                else:
                        scraper.set_pause(True)
                        pause = True
                        print("Scraping paused signal sent.")
                

class SortingThread(QThread):
    finished = pyqtSignal(pd.DataFrame)
    def __init__(self, df, column, sort_algo):
        super().__init__()
        self.df = df.copy()
        self.column = column
        self.sort_algo = sort_algo
        self.sorted_df = None

    def run(self):
        self.sorted_df = self.sort_algo(self.df, self.column)
        self.finished.emit(self.sorted_df)


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
